<a href="https://colab.research.google.com/github/rmishra258/Board-Infinity/blob/master/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
"""

Linear algebra in significantly used in recommender systems - especially colllaborative filtering

Practical use of linear algebra - 
https://towardsdatascience.com/intro-to-recommender-system-collaborative-filtering-64a238194a26
"""

In [0]:
import numpy as np

In [0]:
"""
VECTOR QUANTITY

Sclar - 3 km/h, 35 Knots (does not have direction)

Vector will have magnitude and direction

5 kmph, North 
10 Knots, East 

example = [1,2,3]

"""

In [2]:
vector_1 = np.array([10,20,30,40])

vector_1

array([10, 20, 30, 40])

In [0]:
"""
Group of vectors can be called a matrix
example = [[1,2,3], [4,5,6]]
"""

In [4]:
matrix_1 = np.array([[1,2,3],
                     [4,5,6]])

matrix_1

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
"""
Vector calculations using sclar quanity

Addition
[1,2,3] + 2 = [1+2, 2+2, 3+2] = [3,4,5]

Subraction
[4,6,8] - 2 = [4-2, 6-2, 8-2] = [2,4,6]

Multiplication
[1,2,3] * 2 = [1*2, 2*2, 3*2] = [2,4,6]

Division
[2,4,6] / 2 = [2/2, 4/2, 6/2] = [1,2,3]
"""

In [7]:
#Addition
vec_1 = np.array([1,2,3])
vec_1 + 2

array([3, 4, 5])

In [8]:
#Subraction
vec_2 = np.array([4,6,8])
vec_2 - 2

array([2, 4, 6])

In [9]:
#Multiplication
vec_3 = np.array([1,2,3])
vec_3 * 2

array([2, 4, 6])

In [12]:
#Division
vec_4 = np.array([2,4,6])
vec_4 / 2

array([1., 2., 3.])

In [0]:
"""
Doing mathematical operation on a MATRIX
""" 

In [14]:
#Addition
matrix_1 = np.array([[2,4], [6,8]])
matrix_1 + 10 

array([[12, 14],
       [16, 18]])

In [15]:
#Subraction 
matrix_2 = np.array([[2,4], [6,8]])
matrix_2 - 2

array([[0, 2],
       [4, 6]])

In [16]:
#Multiplication
matrix_3 = np.array([[2,4], [6,8]])
matrix_3 * 2

array([[ 4,  8],
       [12, 16]])

In [20]:
#Division
matrix_4 = np.array([[2,4], [6,8]])
matrix_4 / 2

array([[1., 2.],
       [3., 4.]])

In [0]:
"""
Matrix multiplication

Multiplying a matrix by another martix 

Matrix 1
[[2, 2],
 [3, 2],
 [9, 4]]

3 rows by 2 columns

Martix 2
[6, 8, 9],
[2, 4, 2]]

2 rows by 3 columns

Multiplication as follows

3*2 <=> 2*3

Final matrix will be a 3*3 matrix

Matrix 1 * Matrix 2

Matrix 1 
[[2, 2],
 [3, 2],
 [9, 4]]

Martix 2
[6, 8, 9],
[2, 4, 2]]

Multiply 

Take each rows of the first matrix and multiply them by every columns in second matrix

[[2*6 + 2*2], [2*8 + 2*4], [2*9 + 2*2],
 [3*6 + 2*2], [3*8 + 2*4], [9*9 + 4*2],
 [9*6 + 4*2], [9*8 + 4*4], [9*9 + 4*2]]

 = [[16, 24, 22],
    [22, 32, 89],
    [62, 88, 89]]

Rule of thumb
1) Matrix can only multiply if the Count of the COLUMNS in first matrix is EQUAL to the Count of the ROWS in second matrix
2) The final product will be EQUAL to the Count of the ROWS in first matrix and Count of the COLUMNS in second matrix
"""

In [29]:
matrix_1 = np.array([2,2,3,2,9,4]).reshape(3,2)

matrix_1

array([[2, 2],
       [3, 2],
       [9, 4]])

In [31]:
matrix_2 = np.array([6,8,9,2,4,2]).reshape(2,3)
matrix_2

array([[6, 8, 9],
       [2, 4, 2]])

In [32]:
np.dot(matrix_1, matrix_2)

array([[16, 24, 22],
       [22, 32, 31],
       [62, 88, 89]])

In [0]:
"""
if I change the shape of the first matrix to 2,2 and try to multiply by 2,3 matrix it will give me an error since it does not follow the rule
"""

In [34]:
matrix_1 = np.array([2,2,3,2,9,4,4,6,7]).reshape(3,3)

np.dot(matrix_1, matrix_2)


ValueError: ignored